cli: fix format string clang-10 warning
Fixes:

 cli.c:196:19: error: format string is not a string literal [-Werror=format-nonliteral]

Signed-off-by: Rosen Penev <rosenp@gmail.com>
[split into separate commit]
Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 03dfbbe6fef7639fd20a2b2e0fd97df2ff8e6516)