lua: add missing forward declaration
Fixes following warning reported by clang-10:

  lua/uci.c:1050:1: error: no previous declaration for ‘luaopen_uci’ [-Werror=missing-declarations]

Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 654d7c33da28d492412e1a0fe4463f27d362e9b9)